### ISSUE TITLE
java.lang.NoSuchFieldError: No static field Companion of type Landroid/util/Log$Companion

### ISSUE THREAD

**Issue by subhannaeem** [knocklabs/knock-android#5]
While integrating the knock-android version 0.1.2 into my project, I encountered a runtime error related to the Log class: java.lang.NoSuchFieldError: No static field Companion of type Landroid/util/Log$Companion;. This issue seems to stem from an incorrect reference or usage within the SDK

Steps to Reproduce:

Integrate knock-android version 0.1.2 into an Android project.
Perform actions or initialize the SDK to trigger logging (provide specific steps if possible).
Observe the application crash with the mentioned error.
Expected Behavior:

The SDK should utilize the Android Log class without causing any NoSuchFieldError, allowing for normal operation and logging functionality without crashing.

Actual Behavior:

The application crashes due to a NoSuchFieldError related to the Log class when attempting to log messages or perform actions that involve logging.

Potential Causes:

The SDK might be attempting to access a non-existent Companion object on the Android Log class, which is not a pattern used by the Android SDK.
This could be due to a misinterpretation of Kotlin's static access in Java or a mistaken addition in the SDK's logging mechanism.
Suggested Fixes:

Review the SDK's logging implementation to ensure compatibility with standard Android logging practices, particularly avoiding the use of Companion for the Log class.
Test the logging functionality across different Kotlin and Android versions to catch similar issues in the development phase.
Additional Context:

Android Version: 33
Kotlin Version: 1.9.20
Device/Emulator Specifications: Pixel7
Stack Trace (if applicable):

`FATAL EXCEPTION: main
                                                                                                    Process: io.range.app.dev, PID: 12069
                                                                                                    java.lang.NoSuchFieldError: No static field Companion of type Landroid/util/Log$Companion; in class Landroid/util/Log; or its superclasses (declaration of 'android.util.Log' appears in /system/framework/framework.jar!classes3.dex)`

**Comment by matgar26** [comment]
@subhannaeem Could you try [version 1.0.3](https://github.com/knocklabs/knock-android/releases/tag/0.1.3) and let me know if you are still seeing the issue?

**Comment by subhannaeem** [comment]
@matgar26 this issue is no longer appearing. Thanks for the prompt help
